services:
  postgres:
    image: postgres:latest
    container_name: property_postgres
    environment:
      POSTGRES_DB: property_db
      POSTGRES_USER: property_user
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5433:5432" # Changed to 5433 to avoid conflict
    volumes:
      - postgres_data:/var/lib/postgresql # Updated to /var/lib/postgresql for PostgreSQL 18+
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U property_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: property_redis
    ports:
      - "6380:6379" # Changed to 6380 to avoid potential conflicts
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
